# Form implementation generated from reading ui file '.\templates\dlgFechaBaja.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 335)
        self.calendarBaja = QtWidgets.QCalendarWidget(parent=Dialog)
        self.calendarBaja.setGeometry(QtCore.QRect(1, 2, 401, 261))
        self.calendarBaja.setObjectName("calendarBaja")
        self.txtFechaBaja = QtWidgets.QLineEdit(parent=Dialog)
        self.txtFechaBaja.setGeometry(QtCore.QRect(110, 270, 191, 20))
        self.txtFechaBaja.setObjectName("txtFechaBaja")
        self.btnFechaBaja = QtWidgets.QPushButton(parent=Dialog)
        self.btnFechaBaja.setGeometry(QtCore.QRect(170, 300, 75, 23))
        self.btnFechaBaja.setObjectName("btnFechaBaja")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnFechaBaja.setText(_translate("Dialog", "OK"))
