# Form implementation generated from reading ui file 'jdgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_jdgSalir(object):
    def setupUi(self, jdgSalir):
        jdgSalir.setObjectName("jdgSalir")
        jdgSalir.resize(323, 181)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/Coche.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        jdgSalir.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=jdgSalir)
        self.label.setGeometry(QtCore.QRect(130, 40, 141, 21))
        self.label.setObjectName("label")
        self.btnSalir = QtWidgets.QPushButton(parent=jdgSalir)
        self.btnSalir.setGeometry(QtCore.QRect(80, 110, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        self.btnCancelar = QtWidgets.QPushButton(parent=jdgSalir)
        self.btnCancelar.setGeometry(QtCore.QRect(170, 110, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(jdgSalir)
        QtCore.QMetaObject.connectSlotsByName(jdgSalir)

    def retranslateUi(self, jdgSalir):
        _translate = QtCore.QCoreApplication.translate
        jdgSalir.setWindowTitle(_translate("jdgSalir", "Salir"))
        self.label.setText(_translate("jdgSalir", "¿Deseas salir?"))
        self.btnSalir.setText(_translate("jdgSalir", "Salir"))
        self.btnCancelar.setText(_translate("jdgSalir", "Cancelar"))
