# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgCalendar.sizePolicy().hasHeightForWidth())
        dlgCalendar.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/calendar_office_day_1474.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgCalendar.setWindowIcon(icon)
        dlgCalendar.setModal(True)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=dlgCalendar)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)


    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Calendar"))


class Ui_dlgCalendarfac(object):
        def setupUi(self, dlgCalendarfac):
            dlgCalendarfac.setObjectName("dlgCalendarfac")
            dlgCalendarfac.resize(400, 300)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(dlgCalendarfac.sizePolicy().hasHeightForWidth())
            dlgCalendarfac.setSizePolicy(sizePolicy)
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../../Downloads/calendar_office_day_1474.ico"), QtGui.QIcon.Mode.Normal,
                           QtGui.QIcon.State.Off)
            dlgCalendarfac.setWindowIcon(icon)
            dlgCalendarfac.setModal(True)
            self.calendarWidget = QtWidgets.QCalendarWidget(parent=dlgCalendarfac)
            self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
            self.calendarWidget.setObjectName("calendarWidget")

            self.retranslateUi(dlgCalendarfac)
            QtCore.QMetaObject.connectSlotsByName(dlgCalendarfac)

        def retranslateUi(self, dlgCalendarfac):
            _translate = QtCore.QCoreApplication.translate
            dlgCalendarfac.setWindowTitle(_translate("dlgCalendafac", "Calendar"))